
import java.util.ArrayList;

/**
 *
 * @author s201119359
 */
public class NoohAlaviAssignment23 extends javax.swing.JFrame {

    /**
     * Creates new form NoohAlaviAssignment23
     */
    public NoohAlaviAssignment23() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnConvert = new javax.swing.JButton();
        lblDropzits = new javax.swing.JLabel();
        lblClickwicks = new javax.swing.JLabel();
        lblGazoontights = new javax.swing.JLabel();
        lblFrazoints = new javax.swing.JLabel();
        lblBlointoints = new javax.swing.JLabel();
        lblVrobits = new javax.swing.JLabel();
        txtVrobits = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("$ ZirboinFinancial Currency Exchange $");

        btnConvert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnConvert.setForeground(new java.awt.Color(0, 80, 0));
        btnConvert.setText("- CONVERT -");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        lblDropzits.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblDropzits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDropzits.setText("0 Drobzits");

        lblClickwicks.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblClickwicks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClickwicks.setText("0 Clickwicks");

        lblGazoontights.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblGazoontights.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGazoontights.setText("0 Gazoontights");

        lblFrazoints.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblFrazoints.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrazoints.setText("0 Frazoints");

        lblBlointoints.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblBlointoints.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBlointoints.setText("0 Blointoints");

        lblVrobits.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblVrobits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVrobits.setText("0 Vrobits");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVrobits)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGazoontights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblClickwicks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBlointoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFrazoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVrobits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDropzits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConvert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(22, 22, 22)
                .addComponent(txtVrobits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConvert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(lblDropzits)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClickwicks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGazoontights)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFrazoints)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBlointoints)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVrobits)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        ArrayList<Integer> currency = getCurrency();
        
        lblDropzits.setText(currency.get(0) + " Drobzits");
        lblClickwicks.setText(currency.get(1) + " Clickwicks");
        lblGazoontights.setText(currency.get(2) + " Gazoontights");
        lblFrazoints.setText(currency.get(3) + " Frazoints");
        lblBlointoints.setText(currency.get(4) + " Blointoints");
        lblVrobits.setText(currency.get(5) + " Vrobits");
    }//GEN-LAST:event_btnConvertActionPerformed

    public ArrayList currencyConversion(int vrobits) {
        // Currency values in vrobits
        final int DROBZIT_VAL = 100000,
                CLICKWICK_VAL = 50000,
                GAZOONTIGHT_VAL = 10000,
                FRAZOINT_VAL = 1000,
                BLOINTOIT_VAL = 500;
        
        ArrayList<Integer> currencies = new ArrayList<>();
        
        int drobzits = vrobits / DROBZIT_VAL;
        vrobits -= (drobzits * DROBZIT_VAL);
        currencies.add(drobzits);
        
        int clickwicks = vrobits / CLICKWICK_VAL;
        vrobits -= (clickwicks * CLICKWICK_VAL);
        currencies.add(clickwicks);
        
        int gazoontights = vrobits / GAZOONTIGHT_VAL;
        vrobits -= (gazoontights * GAZOONTIGHT_VAL);
        currencies.add(gazoontights);
        
        int frazoints = vrobits / FRAZOINT_VAL;
        vrobits -= (frazoints * FRAZOINT_VAL);
        currencies.add(frazoints);
        
        int blointoints = vrobits / BLOINTOIT_VAL;
        vrobits -= (blointoints * BLOINTOIT_VAL);
        currencies.add(blointoints);
        
        currencies.add(vrobits);
        
        return currencies;
    }
    
    ArrayList getCurrency() {
        return currencyConversion(Integer.parseInt(txtVrobits.getText()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NoohAlaviAssignment23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NoohAlaviAssignment23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NoohAlaviAssignment23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoohAlaviAssignment23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NoohAlaviAssignment23().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvert;
    private javax.swing.JLabel lblBlointoints;
    private javax.swing.JLabel lblClickwicks;
    private javax.swing.JLabel lblDropzits;
    private javax.swing.JLabel lblFrazoints;
    private javax.swing.JLabel lblGazoontights;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVrobits;
    private javax.swing.JTextField txtVrobits;
    // End of variables declaration//GEN-END:variables
}
