/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author S201119359
 */

import java.text.DecimalFormat;

public class FrmShoppingApp extends javax.swing.JFrame {

    /**
     * Creates new form FrmShoppingApp
     */
    
    public FrmShoppingApp() {
        initComponents();
    }
    
    // Declare and initiate the variables
    
    DecimalFormat df = new DecimalFormat("#.00"); // going to use this to round prices
    
    // drinks
    final double COFFEE_PRICE = 1.79; // the price of this item
    int coffeeQuantity = 0; // the amount that the user wants to buy, defaults to zero
    
    final double ICED_HAT_PRICE = 3.29;
    int icedHatQuantity = 0;
    
    final double HOT_CHOCOLATE_PRICE = 2.49;
    int hotChocolateQuantity = 0;
    
    final double LEMONADE_PRICE = 1.79;
    int lemonadeQuantity = 0;
    
    final double SMOOTHIE_PRICE = 2.49;
    int smoothieQuantity = 0;
    
    // food items
    final double DONUT_PRICE = 1.99;
    int donutQuantity = 0;
    
    final double HIMBITS_10_PRICE = 1.99;
    int himbits10Quantity = 0;
    
    final double HIMBITS_20_PRICE = 3.99;
    int himbits20Quantity = 0;
    
    final double BLUEBERRY_MUFFIN_PRICE = 1.49;
    int blueberryMuffinQuantity = 0;
    
    final double CHOC_CHIP_MUFFIN_PRICE = 1.49;
    int chocChipMuffinQuantity = 0;
    
    final double RASPBERRY_MUFFIN_PRICE = 1.49;
    int raspberryMuffinQuantity = 0;
    
    //variables to calculate total price
    final double TAX_RATE = 0.13; //13%
    double subtotal = 0;
    double taxAmount = 0;
    double totalPrice = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        lblDrinksHeading = new javax.swing.JLabel();
        lblCoffee = new javax.swing.JLabel();
        txtCoffee = new javax.swing.JTextField();
        lblIcedHat = new javax.swing.JLabel();
        txtIcedHat = new javax.swing.JTextField();
        lblHotChocolate = new javax.swing.JLabel();
        txtHotChocolate = new javax.swing.JTextField();
        lblLemonade = new javax.swing.JLabel();
        txtLemonade = new javax.swing.JTextField();
        lblSmoothie = new javax.swing.JLabel();
        txtSmoothie = new javax.swing.JTextField();
        lblFoodItemsHeader = new javax.swing.JLabel();
        lblDonut = new javax.swing.JLabel();
        txtDonut = new javax.swing.JTextField();
        lblHimbits10 = new javax.swing.JLabel();
        txtHimbits10 = new javax.swing.JTextField();
        lblHimbits20 = new javax.swing.JLabel();
        txtHimbits20 = new javax.swing.JTextField();
        lblBlueberryBuffin = new javax.swing.JLabel();
        txtBlueberryMuffin = new javax.swing.JTextField();
        lblChocChipMuffin = new javax.swing.JLabel();
        txtChocChipMuffin = new javax.swing.JTextField();
        lblRaspberryMuffin = new javax.swing.JLabel();
        txtRaspberryMuffin = new javax.swing.JTextField();
        lblPriceHeader = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblSubtotalAmount = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        lblTaxAmount = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        lblTotalPriceAmount = new javax.swing.JLabel();
        btnBuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setIcon(new javax.swing.ImageIcon("U:\\Documents\\NetBeansProjects\\NoohAlaviAssignment5\\logo.png")); // NOI18N

        lblDrinksHeading.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblDrinksHeading.setForeground(new java.awt.Color(222, 71, 71));
        lblDrinksHeading.setText("DRINKS");

        lblCoffee.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblCoffee.setText("Coffee ($1.79)");

        txtCoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCoffee.setText("0");
        txtCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoffeeActionPerformed(evt);
            }
        });

        lblIcedHat.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblIcedHat.setText("Iced Hat © ($3.29)");

        txtIcedHat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIcedHat.setText("0");
        txtIcedHat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIcedHatActionPerformed(evt);
            }
        });

        lblHotChocolate.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblHotChocolate.setText("Hot Chocolate ($2.49)");

        txtHotChocolate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHotChocolate.setText("0");
        txtHotChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHotChocolateActionPerformed(evt);
            }
        });

        lblLemonade.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblLemonade.setText("Freezing Lemonade ($1.79)");

        txtLemonade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLemonade.setText("0");
        txtLemonade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLemonadeActionPerformed(evt);
            }
        });

        lblSmoothie.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSmoothie.setText("Blender Mender Smoothie ($2.49)");

        txtSmoothie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSmoothie.setText("0");
        txtSmoothie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSmoothieActionPerformed(evt);
            }
        });

        lblFoodItemsHeader.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblFoodItemsHeader.setForeground(new java.awt.Color(222, 71, 71));
        lblFoodItemsHeader.setText("FOOD ITEMS");

        lblDonut.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblDonut.setText("Donuts 1 DOZEN ($11.99)");

        txtDonut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDonut.setText("0");
        txtDonut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonutActionPerformed(evt);
            }
        });

        lblHimbits10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblHimbits10.setText("Him Bits © 10 PCK ($1.99)");

        txtHimbits10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHimbits10.setText("0");
        txtHimbits10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHimbits10ActionPerformed(evt);
            }
        });

        lblHimbits20.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblHimbits20.setText("Him Bits © 20 PCK ($3.99)");

        txtHimbits20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHimbits20.setText("0");
        txtHimbits20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHimbits20ActionPerformed(evt);
            }
        });

        lblBlueberryBuffin.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblBlueberryBuffin.setText("Blueberry Muffin ($1.49)");

        txtBlueberryMuffin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBlueberryMuffin.setText("0");
        txtBlueberryMuffin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBlueberryMuffinActionPerformed(evt);
            }
        });

        lblChocChipMuffin.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblChocChipMuffin.setText("Chocolate Chip Muffin ($1.49)");

        txtChocChipMuffin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtChocChipMuffin.setText("0");
        txtChocChipMuffin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChocChipMuffinActionPerformed(evt);
            }
        });

        lblRaspberryMuffin.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblRaspberryMuffin.setText("Raspberry Muffin ($1.49)");

        txtRaspberryMuffin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRaspberryMuffin.setText("0");
        txtRaspberryMuffin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRaspberryMuffinActionPerformed(evt);
            }
        });

        lblPriceHeader.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblPriceHeader.setForeground(new java.awt.Color(222, 71, 71));
        lblPriceHeader.setText("PRICE");

        lblSubtotal.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSubtotal.setText("Subtotal");

        lblSubtotalAmount.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblSubtotalAmount.setText("$0.00");

        lblTax.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblTax.setText("Tax");

        lblTaxAmount.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblTaxAmount.setText("$0.00 (13%)");

        lblTotalPrice.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblTotalPrice.setText("Total Price");

        lblTotalPriceAmount.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblTotalPriceAmount.setText("$0.00");

        btnBuy.setBackground(new java.awt.Color(222, 71, 71));
        btnBuy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBuy.setText("BUY");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoodItemsHeader)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDrinksHeading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHotChocolate)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCoffee)
                                    .addComponent(lblIcedHat)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRaspberryMuffin)
                                            .addComponent(lblBlueberryBuffin)
                                            .addComponent(lblHimbits20)
                                            .addComponent(lblHimbits10)
                                            .addComponent(lblDonut)
                                            .addComponent(lblChocChipMuffin))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtHimbits10, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                            .addComponent(txtHimbits20)
                                            .addComponent(txtBlueberryMuffin)
                                            .addComponent(txtRaspberryMuffin)
                                            .addComponent(txtChocChipMuffin)
                                            .addComponent(txtCoffee)
                                            .addComponent(txtHotChocolate)
                                            .addComponent(txtDonut)
                                            .addComponent(txtIcedHat))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(26, 26, 26)
                                                    .addComponent(lblPriceHeader))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGap(53, 53, 53)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblSmoothie)
                                                        .addComponent(lblLemonade))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblTax)
                                                    .addComponent(lblSubtotal)
                                                    .addComponent(lblTotalPrice))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSubtotalAmount)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtLemonade)
                                                .addComponent(txtSmoothie, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                            .addComponent(lblTaxAmount)
                                            .addComponent(lblTotalPriceAmount)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuy)
                                        .addGap(106, 106, 106)))))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(lblDrinksHeading))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCoffee)
                            .addComponent(txtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLemonade)
                            .addComponent(txtLemonade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIcedHat)
                            .addComponent(txtIcedHat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSmoothie)
                            .addComponent(txtSmoothie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHotChocolate)
                            .addComponent(txtHotChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFoodItemsHeader)
                    .addComponent(lblPriceHeader))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDonut)
                    .addComponent(txtDonut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubtotal)
                    .addComponent(lblSubtotalAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHimbits10)
                    .addComponent(txtHimbits10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTax)
                    .addComponent(lblTaxAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHimbits20)
                    .addComponent(txtHimbits20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPrice)
                    .addComponent(lblTotalPriceAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBlueberryMuffin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBlueberryBuffin, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChocChipMuffin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChocChipMuffin)
                    .addComponent(btnBuy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaspberryMuffin)
                    .addComponent(txtRaspberryMuffin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Update the subtotal, tax, and total price after the user enters in a value
    private void updatePrice() {
	// get data from textfields
        coffeeQuantity = Integer.parseInt(txtCoffee.getText());
        icedHatQuantity = Integer.parseInt(txtIcedHat.getText());
        hotChocolateQuantity = Integer.parseInt(txtHotChocolate.getText());
        lemonadeQuantity = Integer.parseInt(txtLemonade.getText());
        smoothieQuantity = Integer.parseInt(txtSmoothie.getText());
        donutQuantity = Integer.parseInt(txtDonut.getText());
        himbits10Quantity = Integer.parseInt(txtHimbits10.getText());
        himbits20Quantity = Integer.parseInt(txtHimbits20.getText());
        blueberryMuffinQuantity = Integer.parseInt(txtBlueberryMuffin.getText());
        chocChipMuffinQuantity = Integer.parseInt(txtChocChipMuffin.getText());
        raspberryMuffinQuantity = Integer.parseInt(txtRaspberryMuffin.getText());
        
        // calculate subtotal
        subtotal = 0; // reset subtotal

        subtotal += (COFFEE_PRICE * coffeeQuantity)
                + (ICED_HAT_PRICE * icedHatQuantity)
		+ (HOT_CHOCOLATE_PRICE * hotChocolateQuantity)
		+ (LEMONADE_PRICE * lemonadeQuantity)
		+ (SMOOTHIE_PRICE * smoothieQuantity)
		+ (DONUT_PRICE * donutQuantity)
		+ (HIMBITS_10_PRICE * himbits10Quantity)
		+ (HIMBITS_20_PRICE * himbits20Quantity)	
		+ (BLUEBERRY_MUFFIN_PRICE * blueberryMuffinQuantity)
		+ (CHOC_CHIP_MUFFIN_PRICE * chocChipMuffinQuantity)
		+ (RASPBERRY_MUFFIN_PRICE * raspberryMuffinQuantity);
        
        // calculate tax rate and total price
        taxAmount = (subtotal * TAX_RATE);
        totalPrice = subtotal + taxAmount;
        
        // display info
        lblSubtotalAmount.setText("$" + df.format(subtotal));
        lblTaxAmount.setText("$" + df.format(taxAmount) + "(" + TAX_RATE + "%)");
        lblTotalPriceAmount.setText("$" + df.format(totalPrice));
    }
    
    // Runs after the user clicks 'buy', clears all the items to indicate that they completed their purchase
    private void buyItems() {
        txtCoffee.setText("0");
        txtIcedHat.setText("0");
        txtHotChocolate.setText("0");
        txtLemonade.setText("0");
        txtSmoothie.setText("0");
        txtDonut.setText("0");
        txtHimbits10.setText("0");
        txtHimbits20.setText("0");
        txtBlueberryMuffin.setText("0");
        txtChocChipMuffin.setText("0");
        txtRaspberryMuffin.setText("0");
        
        updatePrice(); // so the subtotal, tax rate, and total price all reset as well
    }
    
    // bind all of the textfields to updatePrice()
    private void txtCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoffeeActionPerformed
        updatePrice();
    }//GEN-LAST:event_txtCoffeeActionPerformed

    private void txtLemonadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLemonadeActionPerformed
        updatePrice();
    }//GEN-LAST:event_txtLemonadeActionPerformed

    private void txtIcedHatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIcedHatActionPerformed
        updatePrice();
    }//GEN-LAST:event_txtIcedHatActionPerformed

    private void txtSmoothieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSmoothieActionPerformed
        updatePrice();
    }//GEN-LAST:event_txtSmoothieActionPerformed

    private void txtHotChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHotChocolateActionPerformed
        updatePrice();
    }//GEN-LAST:event_txtHotChocolateActionPerformed

    private void txtDonutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonutActionPerformed
        updatePrice();
    }//GEN-LAST:event_txtDonutActionPerformed

    private void txtHimbits10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHimbits10ActionPerformed
        updatePrice();
    }//GEN-LAST:event_txtHimbits10ActionPerformed

    private void txtHimbits20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHimbits20ActionPerformed
        updatePrice();
    }//GEN-LAST:event_txtHimbits20ActionPerformed

    private void txtBlueberryMuffinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBlueberryMuffinActionPerformed
        updatePrice();
    }//GEN-LAST:event_txtBlueberryMuffinActionPerformed

    private void txtChocChipMuffinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChocChipMuffinActionPerformed
        updatePrice();
    }//GEN-LAST:event_txtChocChipMuffinActionPerformed

    private void txtRaspberryMuffinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRaspberryMuffinActionPerformed
        updatePrice();
    }//GEN-LAST:event_txtRaspberryMuffinActionPerformed

    // run buyItems() when user clicks the 'buy' button
    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        buyItems();
    }//GEN-LAST:event_btnBuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmShoppingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmShoppingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmShoppingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmShoppingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmShoppingApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lblBlueberryBuffin;
    private javax.swing.JLabel lblChocChipMuffin;
    private javax.swing.JLabel lblCoffee;
    private javax.swing.JLabel lblDonut;
    private javax.swing.JLabel lblDrinksHeading;
    private javax.swing.JLabel lblFoodItemsHeader;
    private javax.swing.JLabel lblHimbits10;
    private javax.swing.JLabel lblHimbits20;
    private javax.swing.JLabel lblHotChocolate;
    private javax.swing.JLabel lblIcedHat;
    private javax.swing.JLabel lblLemonade;
    private javax.swing.JLabel lblPriceHeader;
    private javax.swing.JLabel lblRaspberryMuffin;
    private javax.swing.JLabel lblSmoothie;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblSubtotalAmount;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTaxAmount;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lblTotalPriceAmount;
    private javax.swing.JTextField txtBlueberryMuffin;
    private javax.swing.JTextField txtChocChipMuffin;
    private javax.swing.JTextField txtCoffee;
    private javax.swing.JTextField txtDonut;
    private javax.swing.JTextField txtHimbits10;
    private javax.swing.JTextField txtHimbits20;
    private javax.swing.JTextField txtHotChocolate;
    private javax.swing.JTextField txtIcedHat;
    private javax.swing.JTextField txtLemonade;
    private javax.swing.JTextField txtRaspberryMuffin;
    private javax.swing.JTextField txtSmoothie;
    // End of variables declaration//GEN-END:variables
}
