/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author s201119359
 */
public class NoohAlaviAssignment17Frm extends javax.swing.JFrame {

    /**
     * Creates new form NoohAlaviAssignment17Frm
     */
    public NoohAlaviAssignment17Frm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPage = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblCubeRoot = new javax.swing.JLabel();
        txtCubeRoot = new javax.swing.JTextField();
        lblCubeRootAnswer = new javax.swing.JLabel();
        lblDegrees = new javax.swing.JLabel();
        txtDegrees = new javax.swing.JTextField();
        lblDegreesAnswer = new javax.swing.JLabel();
        lblPower = new javax.swing.JLabel();
        txtPower1 = new javax.swing.JTextField();
        txtPower2 = new javax.swing.JTextField();
        lblPowerAnswer = new javax.swing.JLabel();
        lblAbs = new javax.swing.JLabel();
        txtAbs = new javax.swing.JTextField();
        lblAbsAnswer = new javax.swing.JLabel();
        lblHyp = new javax.swing.JLabel();
        txtHyp1 = new javax.swing.JTextField();
        txtHyp2 = new javax.swing.JTextField();
        lblHypAnswer = new javax.swing.JLabel();
        lblSqrt = new javax.swing.JLabel();
        txtSqrt = new javax.swing.JTextField();
        lblSqrtAnswer = new javax.swing.JLabel();
        lblRadians = new javax.swing.JLabel();
        txtRadians = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setBackground(new java.awt.Color(174, 78, 95));
        lblTitle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(174, 78, 95));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Magical Math Methods");

        lblCubeRoot.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblCubeRoot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCubeRoot.setText("Enter an integer. The program will display the CUBE ROOT of the integer.");

        txtCubeRoot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCubeRoot.setText("0");

        lblCubeRootAnswer.setText("0");
        lblCubeRootAnswer.setToolTipText("");

        lblDegrees.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblDegrees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDegrees.setText("Enter an angle in radians. The program will display the angle in DEGREES.");

        txtDegrees.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDegrees.setText("0");

        lblDegreesAnswer.setText("0");
        lblDegreesAnswer.setToolTipText("");

        lblPower.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblPower.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPower.setText("Enter two numbers. The program will display the first number to the power of the second number.");

        txtPower1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPower1.setText("0");

        txtPower2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPower2.setText("0");

        lblPowerAnswer.setText("0");
        lblPowerAnswer.setToolTipText("");

        lblAbs.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblAbs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAbs.setText("Enter a number. The program will display the ABSOLUTE VALUE of the number.");

        txtAbs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAbs.setText("0");

        lblAbsAnswer.setText("0");
        lblAbsAnswer.setToolTipText("");

        lblHyp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblHyp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHyp.setText("Enter the length of two sides of a right angle triangle. The program will display the HYPOTENUSE of the triangle.");

        txtHyp1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHyp1.setText("0");

        txtHyp2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHyp2.setText("0");

        lblHypAnswer.setText("0");
        lblHypAnswer.setToolTipText("");

        lblSqrt.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblSqrt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSqrt.setText("Enter a positive integer. The program will display the SQUARE ROOT of the integer.");

        txtSqrt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSqrt.setText("0");

        lblSqrtAnswer.setText("0");
        lblSqrtAnswer.setToolTipText("");

        lblRadians.setText("Enter an angle in degrees. The program will display the angle in RADIANS.");

        txtRadians.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRadians.setText("0");

        btnCalculate.setBackground(new java.awt.Color(17, 178, 95));
        btnCalculate.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnCalculate.setText("CALCULATE");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        jLabel9.setText("0");
        jLabel9.setToolTipText("");

        javax.swing.GroupLayout pnlPageLayout = new javax.swing.GroupLayout(pnlPage);
        pnlPage.setLayout(pnlPageLayout);
        pnlPageLayout.setHorizontalGroup(
            pnlPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPageLayout.createSequentialGroup()
                .addGroup(pnlPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPageLayout.createSequentialGroup()
                                .addGroup(pnlPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCubeRoot)
                                    .addComponent(lblDegrees)
                                    .addComponent(lblPower)
                                    .addComponent(lblAbs)
                                    .addComponent(lblHyp)
                                    .addComponent(lblSqrt)
                                    .addComponent(lblRadians)
                                    .addGroup(pnlPageLayout.createSequentialGroup()
                                        .addComponent(txtPower1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblPowerAnswer))
                                    .addGroup(pnlPageLayout.createSequentialGroup()
                                        .addGroup(pnlPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtAbs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                                            .addComponent(txtPower2, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addComponent(lblAbsAnswer))
                                    .addGroup(pnlPageLayout.createSequentialGroup()
                                        .addComponent(txtSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblSqrtAnswer))
                                    .addGroup(pnlPageLayout.createSequentialGroup()
                                        .addComponent(txtRadians, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9))
                                    .addGroup(pnlPageLayout.createSequentialGroup()
                                        .addComponent(txtDegrees, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDegreesAnswer))
                                    .addGroup(pnlPageLayout.createSequentialGroup()
                                        .addComponent(txtHyp1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblHypAnswer)))
                                .addGap(0, 10, Short.MAX_VALUE))
                            .addGroup(pnlPageLayout.createSequentialGroup()
                                .addComponent(txtCubeRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCubeRootAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnlPageLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(btnCalculate)))
                .addContainerGap())
            .addGroup(pnlPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPageLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtHyp2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(74, Short.MAX_VALUE)))
        );
        pnlPageLayout.setVerticalGroup(
            pnlPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPageLayout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCubeRoot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCubeRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCubeRootAnswer))
                .addGap(18, 18, 18)
                .addComponent(lblDegrees)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDegrees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDegreesAnswer))
                .addGap(18, 18, 18)
                .addComponent(lblPower)
                .addGroup(pnlPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPageLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtPower1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPower2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPageLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblPowerAnswer)))
                .addGap(18, 18, 18)
                .addComponent(lblAbs)
                .addGap(18, 18, 18)
                .addGroup(pnlPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAbsAnswer))
                .addGap(18, 18, 18)
                .addComponent(lblHyp)
                .addGap(18, 18, 18)
                .addGroup(pnlPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHyp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHypAnswer))
                .addGap(54, 54, 54)
                .addComponent(lblSqrt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSqrtAnswer))
                .addGap(18, 18, 18)
                .addComponent(lblRadians)
                .addGap(18, 18, 18)
                .addGroup(pnlPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRadians, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(btnCalculate)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(pnlPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPageLayout.createSequentialGroup()
                    .addContainerGap(435, Short.MAX_VALUE)
                    .addComponent(txtHyp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(212, 212, 212)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        double num1, num2, answer;

        // Cube root
        num1 = Integer.parseInt(txtCubeRoot.getText());
        answer = num1 * num1 * num1;
        
        lblCubeRootAnswer.setText(Double.toString(answer));
        
        // Radians to degrees
        
        // First number to the power of the second number
        num1 = Integer.parseInt(txtPower1.getText());
        num2 = Integer.parseInt(txtPower2.getText());
        answer = Math.pow(num1, num2);
        
        lblPowerAnswer.setText(Double.toString(answer));
        
        // Absolute value
        num1 = Integer.parseInt(txtAbs.getText());
        answer = Math.abs(num1);
        
        lblAbsAnswer.setText(Double.toString(answer));
        
        // Hypotenuse triangle
        num1 = Integer.parseInt(txtHyp1.getText());
        num2 = Integer.parseInt(txtHyp2.getText());
        
        answer = Math.sqrt(Math.pow(num1, 2) + Math.pow(num2, 2));
        
        lblHypAnswer.setText(Double.toString(answer));
        
        // Square root
        num1 = Integer.parseInt(txtSqrt.getText());
        answer = Math.sqrt(num1);
        
        lblSqrtAnswer.setText(Double.toString(answer));
        
        // Natural logarithm
//        num1 = Integer.parseInt(txtLog.getText());
//        answer = Math.log(num1);
//        
//        lblLog.setText(Double.toString(answer));
    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NoohAlaviAssignment17Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NoohAlaviAssignment17Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NoohAlaviAssignment17Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoohAlaviAssignment17Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NoohAlaviAssignment17Frm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAbs;
    private javax.swing.JLabel lblAbsAnswer;
    private javax.swing.JLabel lblCubeRoot;
    private javax.swing.JLabel lblCubeRootAnswer;
    private javax.swing.JLabel lblDegrees;
    private javax.swing.JLabel lblDegreesAnswer;
    private javax.swing.JLabel lblHyp;
    private javax.swing.JLabel lblHypAnswer;
    private javax.swing.JLabel lblPower;
    private javax.swing.JLabel lblPowerAnswer;
    private javax.swing.JLabel lblRadians;
    private javax.swing.JLabel lblSqrt;
    private javax.swing.JLabel lblSqrtAnswer;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlPage;
    private javax.swing.JTextField txtAbs;
    private javax.swing.JTextField txtCubeRoot;
    private javax.swing.JTextField txtDegrees;
    private javax.swing.JTextField txtHyp1;
    private javax.swing.JTextField txtHyp2;
    private javax.swing.JTextField txtPower1;
    private javax.swing.JTextField txtPower2;
    private javax.swing.JTextField txtRadians;
    private javax.swing.JTextField txtSqrt;
    // End of variables declaration//GEN-END:variables
}
