/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrmAssignment7;

/**
 *
 * @author S201119359
 */
import java.util.Scanner;
import java.text.DecimalFormat;

public class FrmAssignment7 extends javax.swing.JFrame {

    /**
     * Creates new form FrmAssignment7
     */
    public FrmAssignment7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlModifyOrder = new javax.swing.JPanel();
        lblAppTitle = new javax.swing.JLabel();
        lblCoffee = new javax.swing.JLabel();
        btnSubtractCoffee = new javax.swing.JButton();
        txtCoffee = new javax.swing.JTextField();
        btnAddCoffee = new javax.swing.JButton();
        lblDonuts = new javax.swing.JLabel();
        btnSubtractDonuts = new javax.swing.JButton();
        txtDonuts = new javax.swing.JTextField();
        btnAddDonuts = new javax.swing.JButton();
        lblHimbits = new javax.swing.JLabel();
        btnSubtractHimbits = new javax.swing.JButton();
        txtHimbits = new javax.swing.JTextField();
        btnAddHimbits = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();
        pnlCompleteOrder = new javax.swing.JPanel();
        lblAppTitle1 = new javax.swing.JLabel();
        lblReceiptTitle = new javax.swing.JLabel();
        lblCoffeeReceipt = new javax.swing.JLabel();
        lblDonutsReceipt = new javax.swing.JLabel();
        lblHimbitsReceipt = new javax.swing.JLabel();
        lblSubtotalReceipt = new javax.swing.JLabel();
        lblTaxAmountReceipt = new javax.swing.JLabel();
        lblDiscountReceipt = new javax.swing.JLabel();
        lblTotalPriceReceipt = new javax.swing.JLabel();
        btnModifyOrder = new javax.swing.JButton();
        btnBuyItems = new javax.swing.JButton();
        lblDiscountTitle = new javax.swing.JLabel();
        lblDiscount15 = new javax.swing.JLabel();
        lblDonutDiscount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAppTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppTitle.setIcon(new javax.swing.ImageIcon("U:\\Documents\\NetBeansProjects\\NoohAlaviAssignment7\\logo.png")); // NOI18N
        lblAppTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblCoffee.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCoffee.setText("Coffee ($1.79)");

        btnSubtractCoffee.setBackground(new java.awt.Color(253, 241, 157));
        btnSubtractCoffee.setText("-");
        btnSubtractCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractCoffeeActionPerformed(evt);
            }
        });

        txtCoffee.setBackground(new java.awt.Color(253, 241, 157));
        txtCoffee.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtCoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCoffee.setText("0");
        txtCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoffeeActionPerformed(evt);
            }
        });

        btnAddCoffee.setBackground(new java.awt.Color(253, 241, 157));
        btnAddCoffee.setText("+");
        btnAddCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCoffeeActionPerformed(evt);
            }
        });

        lblDonuts.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblDonuts.setText("Donuts ($0.99)");

        btnSubtractDonuts.setBackground(new java.awt.Color(253, 241, 157));
        btnSubtractDonuts.setText("-");
        btnSubtractDonuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractDonutsActionPerformed(evt);
            }
        });

        txtDonuts.setBackground(new java.awt.Color(253, 241, 157));
        txtDonuts.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtDonuts.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDonuts.setText("0");

        btnAddDonuts.setBackground(new java.awt.Color(253, 241, 157));
        btnAddDonuts.setText("+");
        btnAddDonuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDonutsActionPerformed(evt);
            }
        });

        lblHimbits.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblHimbits.setText("Himbits © 10 PCK ($3.29)");

        btnSubtractHimbits.setBackground(new java.awt.Color(253, 241, 157));
        btnSubtractHimbits.setText("-");
        btnSubtractHimbits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractHimbitsActionPerformed(evt);
            }
        });

        txtHimbits.setBackground(new java.awt.Color(253, 241, 157));
        txtHimbits.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtHimbits.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHimbits.setText("0");
        txtHimbits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHimbitsActionPerformed(evt);
            }
        });

        btnAddHimbits.setBackground(new java.awt.Color(253, 241, 157));
        btnAddHimbits.setText("+");
        btnAddHimbits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHimbitsActionPerformed(evt);
            }
        });

        btnCheckout.setBackground(new java.awt.Color(222, 71, 71));
        btnCheckout.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnCheckout.setText("PROCEED TO CHECKOUT");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlModifyOrderLayout = new javax.swing.GroupLayout(pnlModifyOrder);
        pnlModifyOrder.setLayout(pnlModifyOrderLayout);
        pnlModifyOrderLayout.setHorizontalGroup(
            pnlModifyOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModifyOrderLayout.createSequentialGroup()
                .addComponent(lblAppTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlModifyOrderLayout.createSequentialGroup()
                .addGroup(pnlModifyOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlModifyOrderLayout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addGroup(pnlModifyOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHimbits)
                            .addComponent(lblDonuts, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlModifyOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlModifyOrderLayout.createSequentialGroup()
                                .addComponent(btnSubtractHimbits, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtHimbits, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddHimbits, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlModifyOrderLayout.createSequentialGroup()
                                .addComponent(btnSubtractCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlModifyOrderLayout.createSequentialGroup()
                                .addComponent(btnSubtractDonuts, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDonuts, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddDonuts, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlModifyOrderLayout.createSequentialGroup()
                        .addGap(446, 446, 446)
                        .addComponent(btnCheckout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlModifyOrderLayout.setVerticalGroup(
            pnlModifyOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModifyOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAppTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(pnlModifyOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCoffee)
                    .addComponent(btnSubtractCoffee)
                    .addComponent(txtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCoffee))
                .addGap(18, 18, 18)
                .addGroup(pnlModifyOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDonuts)
                    .addComponent(btnSubtractDonuts)
                    .addComponent(txtDonuts, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddDonuts))
                .addGap(18, 18, 18)
                .addGroup(pnlModifyOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHimbits)
                    .addComponent(btnSubtractHimbits)
                    .addComponent(txtHimbits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddHimbits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );

        pnlCompleteOrder.setVisible(false);

        lblAppTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppTitle1.setIcon(new javax.swing.ImageIcon("U:\\Documents\\NetBeansProjects\\NoohAlaviAssignment7\\logo.png")); // NOI18N
        lblAppTitle1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblReceiptTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblReceiptTitle.setForeground(new java.awt.Color(222, 71, 71));
        lblReceiptTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReceiptTitle.setText("Your Order");

        lblCoffeeReceipt.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCoffeeReceipt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCoffeeReceipt.setText("COFFEES (x0).......... $0.00");

        lblDonutsReceipt.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblDonutsReceipt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDonutsReceipt.setText("DONUTS (x0).......... $0.00");

        lblHimbitsReceipt.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblHimbitsReceipt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHimbitsReceipt.setText("HIMBITS © 10 PCK (x0).......... $0.00");

        lblSubtotalReceipt.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblSubtotalReceipt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtotalReceipt.setText("SUBTOTAL.......... $0.00");

        lblTaxAmountReceipt.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblTaxAmountReceipt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTaxAmountReceipt.setText("TAX AMOUNT (13%).......... $0.00");

        lblDiscountReceipt.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblDiscountReceipt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiscountReceipt.setText("DISCOUNT AMOUNT (15%).......... $0.00");
        lblDiscountReceipt.setVisible(false);

        lblTotalPriceReceipt.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblTotalPriceReceipt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalPriceReceipt.setText("TOTAL PRICE.......... $0.00");

        btnModifyOrder.setBackground(new java.awt.Color(222, 71, 71));
        btnModifyOrder.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnModifyOrder.setText("MODIFY ORDER");
        btnModifyOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyOrderActionPerformed(evt);
            }
        });

        btnBuyItems.setBackground(new java.awt.Color(71, 222, 71));
        btnBuyItems.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnBuyItems.setText("BUY");
        btnBuyItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyItemsActionPerformed(evt);
            }
        });

        lblDiscountTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblDiscountTitle.setForeground(new java.awt.Color(222, 71, 71));
        lblDiscountTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiscountTitle.setText("LIMITED TIME OFFERS");
        lblDiscountTitle.setVisible(false);

        lblDiscount15.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblDiscount15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiscount15.setText("15% DISCOUNT FOR ORDERS OVER $100.00!");
        lblDiscount15.setVisible(false);

        lblDonutDiscount.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblDonutDiscount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDonutDiscount.setText("BUY TWO DONUTS FOR THE PRICE OF ONE!");
        lblDonutDiscount.setVisible(false);

        javax.swing.GroupLayout pnlCompleteOrderLayout = new javax.swing.GroupLayout(pnlCompleteOrder);
        pnlCompleteOrder.setLayout(pnlCompleteOrderLayout);
        pnlCompleteOrderLayout.setHorizontalGroup(
            pnlCompleteOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCompleteOrderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCompleteOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnModifyOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuyItems, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(482, 482, 482))
            .addGroup(pnlCompleteOrderLayout.createSequentialGroup()
                .addGroup(pnlCompleteOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCompleteOrderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCompleteOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAppTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblReceiptTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlCompleteOrderLayout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addGroup(pnlCompleteOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCompleteOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblHimbitsReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDonutsReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCoffeeReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTaxAmountReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiscountReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalPriceReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubtotalReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 449, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlCompleteOrderLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlCompleteOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDiscount15, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addComponent(lblDiscountTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addComponent(lblDonutDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCompleteOrderLayout.setVerticalGroup(
            pnlCompleteOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompleteOrderLayout.createSequentialGroup()
                .addComponent(lblAppTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblReceiptTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCoffeeReceipt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDonutsReceipt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHimbitsReceipt)
                .addGap(22, 22, 22)
                .addComponent(lblSubtotalReceipt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDiscountReceipt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTaxAmountReceipt)
                .addGap(24, 24, 24)
                .addComponent(lblTotalPriceReceipt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDiscountTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lblDiscount15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDonutDiscount)
                .addGap(27, 27, 27)
                .addComponent(btnBuyItems, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModifyOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlModifyOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 1134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 62, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlCompleteOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlModifyOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlCompleteOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // initialize and define variables
    Scanner keyedInput = new Scanner(System.in);
    DecimalFormat df = new DecimalFormat("0.00");

    final double COFFEE_PRICE = 1.79;
    final double DONUTS_PRICE = .99;
    final double HIMBITS_PRICE = 3.29;
    
    final double TAX_RATE = 0.13; // 13%
    final double DISCOUNT_RATE = 0.15; // 15%
    
    final double START_SHOW_DISCOUNT = 85; // if user subtotal is this #, tell them about discount
    final double DISCOUNT_MINIMUM = 100; // if user has over this #, apply DISCOUNT_RATE
    
    double subtotal = 0;
    double discountedAmount = 0;
    double taxAmount = 0;
    double finalPrice = 0;
    
    private int getItemAmount(javax.swing.JTextField txtItem) {
        return Integer.parseInt(txtItem.getText());
    }

    private double[] calculateTotalPrice(Boolean isEligibleForDiscount) {
        double discountAmount = 0;
        
        // Calculate subtotal
        
        double totalDonutsPrice = getItemAmount(txtDonuts) * DONUTS_PRICE;
        double totalHimbitsPrice = getItemAmount(txtHimbits) * HIMBITS_PRICE;
        double totalCoffeePrice = getItemAmount(txtCoffee) * COFFEE_PRICE;

        if (isEligibleForDiscount) {
            totalDonutsPrice -= DONUTS_PRICE; // remove price of ONE donut
        }
        
        subtotal = totalCoffeePrice + totalDonutsPrice + totalHimbitsPrice;

        // TODO: Apply donut discount if applicable
        
        
        // Apply discount if applicable
        if (subtotal >= DISCOUNT_MINIMUM) {
            discountAmount = subtotal * DISCOUNT_RATE;
        }
        discountedAmount = subtotal - discountAmount;
        
        // Calculate tax amount
        taxAmount = discountedAmount * TAX_RATE;

        // Calculate total price
        finalPrice = discountedAmount + taxAmount;
        
        // Return all the prices
        double[] prices = {totalCoffeePrice, totalDonutsPrice, totalHimbitsPrice, 
            subtotal, discountAmount, taxAmount, finalPrice};
        return prices;
    }
    
    private void addItem(javax.swing.JTextField txtItem) {
        txtItem.setText(
            String.valueOf(
                getItemAmount(txtItem) + 1
            )
        );
    }
    
    private void subItem(javax.swing.JTextField txtItem) {
        int updatedAmount = getItemAmount(txtItem) - 1;
        
        if (updatedAmount >= 0) { //make sure it never goes into a negative number
            txtItem.setText(
                String.valueOf(
                    getItemAmount(txtItem) - 1
                )
            );
        }
    }
    
    private void modifyOrder() {
        // Go back to modify order page
        pnlModifyOrder.setVisible(true);
        pnlCompleteOrder.setVisible(false);

        // hide discount labels since they may no longer be eligible
        lblDiscountReceipt.setVisible(false);
        lblDiscountTitle.setVisible(false);
        lblDiscount15.setVisible(false);
        lblDonutDiscount.setVisible(false);
    }

    private void txtCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoffeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCoffeeActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        Boolean isEligibleForDiscount = false;

        int numberOfDonuts = getItemAmount(txtDonuts);
        int numberOfCoffees = getItemAmount(txtCoffee);
        int numberOfHimbits = getItemAmount(txtHimbits);
        
        // check for donut discount
        if (numberOfDonuts < 2) {
            lblDiscountTitle.setVisible(true);
            lblDonutDiscount.setVisible(true);
        } else {
            isEligibleForDiscount = true;
        }

        // calculate total price
        double[] prices = calculateTotalPrice(isEligibleForDiscount);

        // hide main GUI
        pnlModifyOrder.setVisible(false);
        pnlCompleteOrder.setVisible(true);
        
        // output info to user        
        lblCoffeeReceipt.setText("COFFEES (x" + numberOfCoffees + ").......... $" + df.format(prices[0]));
        lblDonutsReceipt.setText("DONUTS (x" + numberOfDonuts + ").......... $" + df.format(prices[1]));
        lblHimbitsReceipt.setText("HIMBITS © (x" + numberOfHimbits + ").......... $" + df.format(prices[2]));
        lblSubtotalReceipt.setText("SUBTOTAL.......... $" + df.format(prices[3]));
        lblDiscountReceipt.setText("DISCOUNT AMOUNT (15%).......... $" + df.format(prices[4]));
        lblTaxAmountReceipt.setText("TAX AMOUNT (13%).......... $" + df.format(prices[5]));
        lblTotalPriceReceipt.setText("TOTAL PRICE.......... $" + df.format(prices[6]));
        
        // show lblDiscount15 if order is >=85 and <100
        if (prices[3] >= START_SHOW_DISCOUNT && prices[3] < DISCOUNT_MINIMUM) {
            lblDiscountTitle.setVisible(true);
            lblDiscount15.setVisible(true);
        }
        
        // only show "lblDiscountReceipt" if user is getting a discount
        if (prices[4] > 0) {
            lblDiscountReceipt.setVisible(true);
        }
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void txtHimbitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHimbitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHimbitsActionPerformed

    private void btnSubtractCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractCoffeeActionPerformed
        subItem(txtCoffee);
    }//GEN-LAST:event_btnSubtractCoffeeActionPerformed

    private void btnAddCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCoffeeActionPerformed
        addItem(txtCoffee);
    }//GEN-LAST:event_btnAddCoffeeActionPerformed

    private void btnAddDonutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDonutsActionPerformed
        addItem(txtDonuts);
    }//GEN-LAST:event_btnAddDonutsActionPerformed

    private void btnAddHimbitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHimbitsActionPerformed
        addItem(txtHimbits);
    }//GEN-LAST:event_btnAddHimbitsActionPerformed

    private void btnSubtractDonutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractDonutsActionPerformed
        subItem(txtDonuts);
    }//GEN-LAST:event_btnSubtractDonutsActionPerformed

    private void btnSubtractHimbitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractHimbitsActionPerformed
        subItem(txtHimbits);
    }//GEN-LAST:event_btnSubtractHimbitsActionPerformed

    private void btnModifyOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyOrderActionPerformed
        modifyOrder();
    }//GEN-LAST:event_btnModifyOrderActionPerformed

    private void btnBuyItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyItemsActionPerformed
        modifyOrder(); // go back to order page
        
        // clear all the numbers
        txtCoffee.setText("0");
        txtDonuts.setText("0");
        txtHimbits.setText("0");
    }//GEN-LAST:event_btnBuyItemsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAssignment7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAssignment7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAssignment7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAssignment7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAssignment7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCoffee;
    private javax.swing.JButton btnAddDonuts;
    private javax.swing.JButton btnAddHimbits;
    private javax.swing.JButton btnBuyItems;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnModifyOrder;
    private javax.swing.JButton btnSubtractCoffee;
    private javax.swing.JButton btnSubtractDonuts;
    private javax.swing.JButton btnSubtractHimbits;
    private javax.swing.JLabel lblAppTitle;
    private javax.swing.JLabel lblAppTitle1;
    private javax.swing.JLabel lblCoffee;
    private javax.swing.JLabel lblCoffeeReceipt;
    private javax.swing.JLabel lblDiscount15;
    private javax.swing.JLabel lblDiscountReceipt;
    private javax.swing.JLabel lblDiscountTitle;
    private javax.swing.JLabel lblDonutDiscount;
    private javax.swing.JLabel lblDonuts;
    private javax.swing.JLabel lblDonutsReceipt;
    private javax.swing.JLabel lblHimbits;
    private javax.swing.JLabel lblHimbitsReceipt;
    private javax.swing.JLabel lblReceiptTitle;
    private javax.swing.JLabel lblSubtotalReceipt;
    private javax.swing.JLabel lblTaxAmountReceipt;
    private javax.swing.JLabel lblTotalPriceReceipt;
    private javax.swing.JPanel pnlCompleteOrder;
    private javax.swing.JPanel pnlModifyOrder;
    private javax.swing.JTextField txtCoffee;
    private javax.swing.JTextField txtDonuts;
    private javax.swing.JTextField txtHimbits;
    // End of variables declaration//GEN-END:variables
}
