/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author s201119359
 */
public class FrmQuoteGenerator extends javax.swing.JFrame {

    /**
     * Creates new form FrmQuoteGenerator
     */
    public FrmQuoteGenerator() {
        initComponents();
    }
    
    class Quote {
        
        String quote, quotee;
        
        public Quote(String quote_, String quotee_) {
            quote = quote_;
            quotee = quotee_;
        }
    }
    
    private double generateRandomNumber(int minNumber, int maxNumber) {
        return minNumber + (int)(Math.random() * ((maxNumber - minNumber) + 1));
    }
    
    private Quote getQuote() {
        Quote quote = new Quote("", "");
        return quote;
    }
    
    Quote[] quotes = {
        new Quote("Do or do not, there is no try.", "Yoda"),
        new Quote("Learn as if you will live forever, live like you will die tomorrow", "Mahatma Gandhi"),
        new Quote("Experience is a hard teacher because she gives the test first, the lesson afterwards.", "Vernon Sanders Law"),
        new Quote("You never know. You hope for the best, then make do with what you get.", "Nick Fury"),
        new Quote("Education is the most powerful weapon which you can use to change the world.", "Nelson Mandela"),
        new Quote("Opportunities don't happen, you create them.", "Chris Grosser"),
        new Quote("Life is like riding a bicycle. To keep your balance you must keep moving.", "Albert Einstein")
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmQuoteGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmQuoteGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmQuoteGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmQuoteGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmQuoteGenerator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
